In [13]:
import numpy as np

input_seq1 = np.array([10,20,30,40,50,60,70,80,90,100])
input_seq2 = np.array([15,25,35,45,55,65,75,85,95,105])

out_seq = np.array([input_seq1[i]+input_seq2[i] for i in range(len(input_seq1))])

input_seq1 = input_seq1.reshape((len(input_seq1), 1))
input_seq2 = input_seq2.reshape((len(input_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))
dataset = np.hstack((input_seq1, input_seq2, out_seq))

time_steps = 3

def split_seq(seq,steps):
    X, y= [],[]
    for i in range(len(seq)):
        end = i + steps
        if end > len(seq)-1:
            break
        X_seq = seq[i:end,:-1]
        y_seq = seq[end-1,-1]
        X.append(X_seq)
        y.append(y_seq)
    return np.array(X),np.array(y)       


X,y = split_seq(dataset, time_steps)

# show the sample data
for i in range(len(X)):
    print(X[i], y[i])
    
n_features = X.shape[2]

[[10 15]
 [20 25]
 [30 35]] 65
[[20 25]
 [30 35]
 [40 45]] 85
[[30 35]
 [40 45]
 [50 55]] 105
[[40 45]
 [50 55]
 [60 65]] 125
[[50 55]
 [60 65]
 [70 75]] 145
[[60 65]
 [70 75]
 [80 85]] 165
[[70 75]
 [80 85]
 [90 95]] 185


In [30]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

model = Sequential()
model.add(LSTM(50, activation = 'relu', input_shape = (time_steps,n_features)))
model.add(Dense(1))
model.compile(optimizer = 'adam', loss = 'mse')

In [31]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_6 (LSTM)                (None, 50)                10600     
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 51        
Total params: 10,651
Trainable params: 10,651
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.fit(X,y,epochs = 50, verbose = 1)

Epoch 1/50
7/7 [==============================] - 0s 708us/step - loss: 91.6072
Epoch 2/50
7/7 [==============================] - 0s 705us/step - loss: 87.3475
Epoch 3/50
7/7 [==============================] - 0s 634us/step - loss: 86.6027
Epoch 4/50
7/7 [==============================] - 0s 621us/step - loss: 87.6724
Epoch 5/50
7/7 [==============================] - 0s 1ms/step - loss: 89.1958
Epoch 6/50
7/7 [==============================] - 0s 1ms/step - loss: 90.1393
Epoch 7/50
7/7 [==============================] - 0s 2ms/step - loss: 89.7205
Epoch 8/50
7/7 [==============================] - 0s 1ms/step - loss: 87.5609
Epoch 9/50
7/7 [==============================] - 0s 1ms/step - loss: 84.0196
Epoch 10/50
7/7 [==============================] - 0s 2ms/step - loss: 80.6547
Epoch 11/50
7/7 [==============================] - 0s 1ms/step - loss: 77.8538
Epoch 12/50
7/7 [==============================] - 0s 1ms/step - loss: 74.2512
Epoch 13/50
7/7 [==============================] - 0s

In [35]:
x_input = np.array([[80,85],[90,95],[95,100]])
x_input = x_input.reshape((1,time_steps, n_features))
y_ = model.predict(x_input, verbose =1)
print(y_)

1/1 [==============================] - 0s 1ms/step
[[204.20636]]
